//! Differential test against two independent Python implementations
//! (pyemv 1.5 and psec) on 60 random cases, generated by
//! `scripts/gen-differential-vectors.py` (seeded, reproducible).

use cardcrypto::emv::*;
use cardcrypto::{cvv, pin, pinblock};
use serde_json::Value;

fn b<const N: usize>(v: &Value) -> [u8; N] {
    hex::decode(v.as_str().unwrap())
        .unwrap()
        .try_into()
        .unwrap()
}
fn s(v: &Value) -> &str {
    v.as_str().unwrap()
}

#[test]
fn matches_pyemv_and_psec() {
    let cases: Vec<Value> = serde_json::from_str(include_str!("data/differential.json")).unwrap();
    assert_eq!(cases.len(), 60);
    for c in &cases {
        let imk: [u8; 16] = b(&c["imk"]);
        let (pan, psn, p) = (s(&c["pan"]), s(&c["psn"]), s(&c["pin"]));
        let mk_a = derive_icc_mk_a(&imk, pan, psn).unwrap();
        let mk_b = derive_icc_mk_b(&imk, pan, psn).unwrap();
        assert_eq!(mk_a, b::<16>(&c["mk_a"]), "mk_a {pan}");
        assert_eq!(mk_b, b::<16>(&c["mk_b"]), "mk_b {pan}");

        let t = &c["txn"];
        let mut d = ArqcData {
            amount_authorised: b(&t["9F02"]),
            amount_other: b(&t["9F03"]),
            terminal_country: b(&t["9F1A"]),
            tvr: b(&t["95"]),
            currency: b(&t["5F2A"]),
            txn_date: b(&t["9A"]),
            txn_type: b::<1>(&t["9C"])[0],
            unpredictable: b(&t["9F37"]),
            aip: b(&t["82"]),
            atc: b(&t["9F36"]),
            iad: hex::decode(s(&c["cvn10"]["iad"])).unwrap(),
        };
        let mk10 = Cvn::Visa10.icc_mk(&imk, pan, psn).unwrap();
        let arqc10 = Cvn::Visa10.generate_arqc(&mk10, &d).unwrap();
        assert_eq!(arqc10, b::<8>(&c["cvn10"]["arqc"]), "cvn10 arqc {pan}");
        assert_eq!(
            arpc_method1(&mk10, &arqc10, b"00"),
            b::<8>(&c["cvn10"]["arpc_3030"])
        );

        d.iad = hex::decode(s(&c["cvn18"]["iad"])).unwrap();
        let mk18 = Cvn::Visa18.icc_mk(&imk, pan, psn).unwrap();
        let arqc18 = Cvn::Visa18.generate_arqc(&mk18, &d).unwrap();
        assert_eq!(arqc18, b::<8>(&c["cvn18"]["arqc"]), "cvn18 arqc {pan}");
        let sk = Cvn::Visa18.ac_key(&mk18, d.atc);
        assert_eq!(
            arpc_method2(&sk, &arqc18, &b(&c["cvn18"]["csu"]), &[]).unwrap(),
            b::<4>(&c["cvn18"]["arpc"])
        );

        let pvk: [u8; 16] = b(&c["pvk"]);
        assert_eq!(pin::visa_pvv(&pvk, 1, p, pan).unwrap(), s(&c["pvv_pvki1"]));
        assert_eq!(pinblock::encode_iso0(p, pan).unwrap(), b::<8>(&c["iso0"]));
        assert_eq!(
            cvv::cvv(&pvk, pan, s(&c["expiry"]), "101").unwrap(),
            s(&c["cvv_101"])
        );
    }
}
