-- Issuer back office schema. Portable between PostgreSQL and H2 (PostgreSQL mode).

-- Double-entry ledger -------------------------------------------------------
CREATE TABLE ledger_accounts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(64)  NOT NULL UNIQUE,
    kind          VARCHAR(32)  NOT NULL,
    normal_side   CHAR(1)      NOT NULL CHECK (normal_side IN ('D', 'C')),
    currency      VARCHAR(3)   NOT NULL,
    -- Materialised balance on the account's normal side; always equals the
    -- sum of its postings (checked by the trial balance endpoint).
    balance_minor BIGINT       NOT NULL DEFAULT 0
);

CREATE TABLE journal_entries (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_type  VARCHAR(32)  NOT NULL,
    -- Business reference; unique so every posting is idempotent.
    reference   VARCHAR(128) NOT NULL UNIQUE,
    description VARCHAR(255),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE postings (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id          BIGINT  NOT NULL REFERENCES journal_entries (id),
    ledger_account_id BIGINT  NOT NULL REFERENCES ledger_accounts (id),
    direction         CHAR(1) NOT NULL CHECK (direction IN ('D', 'C')),
    amount_minor      BIGINT  NOT NULL CHECK (amount_minor > 0)
);
CREATE INDEX ix_postings_account ON postings (ledger_account_id);
CREATE INDEX ix_postings_entry ON postings (entry_id);

-- Cards and cardholder accounts ---------------------------------------------
CREATE TABLE card_accounts (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holder_name        VARCHAR(100) NOT NULL,
    currency           VARCHAR(3)   NOT NULL,
    credit_limit_minor BIGINT       NOT NULL DEFAULT 0,
    held_minor         BIGINT       NOT NULL DEFAULT 0 CHECK (held_minor >= 0),
    ledger_account_id  BIGINT       NOT NULL REFERENCES ledger_accounts (id),
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE cards (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id             BIGINT      NOT NULL REFERENCES card_accounts (id),
    -- HMAC-SHA256(PAN) truncated; the back office never stores PANs.
    pan_ref                VARCHAR(64) NOT NULL UNIQUE,
    last4                  VARCHAR(4)  NOT NULL,
    expiry                 VARCHAR(4)  NOT NULL,
    status                 VARCHAR(16) NOT NULL,
    pvv                    VARCHAR(4)  NOT NULL,
    pvki                   SMALLINT    NOT NULL,
    service_code           VARCHAR(3)  NOT NULL,
    psn                    VARCHAR(2)  NOT NULL,
    cvn                    SMALLINT    NOT NULL,
    per_txn_limit_minor    BIGINT      NOT NULL,
    daily_cash_limit_minor BIGINT      NOT NULL,
    daily_txn_count_limit  INT         NOT NULL,
    updated_at             TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Authorizations and holds --------------------------------------------------
CREATE TABLE authorizations (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_ref       VARCHAR(80) NOT NULL UNIQUE,
    card_id        BIGINT      NOT NULL REFERENCES cards (id),
    account_id     BIGINT      NOT NULL REFERENCES card_accounts (id),
    parent_auth_id BIGINT REFERENCES authorizations (id),
    amount_minor   BIGINT      NOT NULL,
    held_minor     BIGINT      NOT NULL CHECK (held_minor >= 0),
    cleared_minor  BIGINT      NOT NULL DEFAULT 0,
    currency       VARCHAR(3)  NOT NULL,
    txn_type       VARCHAR(16) NOT NULL,
    mcc            VARCHAR(4),
    merchant_name  VARCHAR(64),
    terminal_id    VARCHAR(16),
    rrn            VARCHAR(12),
    stan           VARCHAR(6),
    auth_code      VARCHAR(6),
    response_code  VARCHAR(2)  NOT NULL,
    status         VARCHAR(24) NOT NULL,
    source         VARCHAR(24) NOT NULL,
    overdraft      BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at     TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_auth_card_status ON authorizations (card_id, status);
CREATE INDEX ix_auth_status_expiry ON authorizations (status, expires_at);

CREATE TABLE reversals (
    reversal_ref             VARCHAR(120) PRIMARY KEY,
    auth_ref                 VARCHAR(80)  NOT NULL,
    replacement_amount_minor BIGINT,
    status                   VARCHAR(24)  NOT NULL,
    created_at               TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE advices (
    advice_id     VARCHAR(120) PRIMARY KEY,
    source        VARCHAR(24)  NOT NULL,
    auth_ref      VARCHAR(80)  NOT NULL,
    response_code VARCHAR(2)   NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Clearing ------------------------------------------------------------------
CREATE TABLE clearing_files (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id          VARCHAR(64) NOT NULL UNIQUE,
    processing_date  DATE        NOT NULL,
    sender           VARCHAR(32) NOT NULL,
    record_count     INT         NOT NULL,
    hash_total_minor BIGINT      NOT NULL,
    received_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE clearing_records (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id           BIGINT      NOT NULL REFERENCES clearing_files (id),
    record_id         VARCHAR(64) NOT NULL UNIQUE,
    record_type       VARCHAR(4)  NOT NULL,
    arn               VARCHAR(23) NOT NULL,
    card_id           BIGINT REFERENCES cards (id),
    authorization_id  BIGINT REFERENCES authorizations (id),
    dispute_id        BIGINT,
    auth_code         VARCHAR(6),
    rrn               VARCHAR(12),
    amount_minor      BIGINT      NOT NULL,
    currency          VARCHAR(3)  NOT NULL,
    mcc               VARCHAR(4),
    merchant_name     VARCHAR(64),
    txn_date          DATE,
    presentment_seq   INT,
    presentment_count INT,
    outcome           VARCHAR(32) NOT NULL,
    journal_entry_id  BIGINT REFERENCES journal_entries (id)
);
CREATE INDEX ix_clearing_arn ON clearing_records (arn);

-- Disputes ------------------------------------------------------------------
CREATE TABLE dispute_reason_codes (
    code               VARCHAR(8)   PRIMARY KEY,
    network            VARCHAR(16)  NOT NULL,
    description        VARCHAR(128) NOT NULL,
    chargeback_days    INT          NOT NULL,
    representment_days INT          NOT NULL,
    prearb_days        INT          NOT NULL,
    required_evidence  VARCHAR(128) NOT NULL
);

CREATE TABLE disputes (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    presentment_id         BIGINT      NOT NULL REFERENCES clearing_records (id),
    arn                    VARCHAR(23) NOT NULL,
    card_id                BIGINT      NOT NULL REFERENCES cards (id),
    account_id             BIGINT      NOT NULL REFERENCES card_accounts (id),
    reason_code            VARCHAR(8)  NOT NULL REFERENCES dispute_reason_codes (code),
    amount_minor           BIGINT      NOT NULL CHECK (amount_minor > 0),
    currency               VARCHAR(3)  NOT NULL,
    state                  VARCHAR(24) NOT NULL,
    provisional_credit     BOOLEAN     NOT NULL,
    opened_at              TIMESTAMP WITH TIME ZONE NOT NULL,
    chargeback_deadline    DATE        NOT NULL,
    representment_deadline DATE,
    prearb_deadline        DATE,
    closed_at              TIMESTAMP WITH TIME ZONE
);
CREATE INDEX ix_disputes_state ON disputes (state);

CREATE TABLE dispute_evidence (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dispute_id    BIGINT       NOT NULL REFERENCES disputes (id),
    evidence_type VARCHAR(32)  NOT NULL,
    description   VARCHAR(255) NOT NULL,
    submitted_by  VARCHAR(32)  NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE dispute_events (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dispute_id BIGINT      NOT NULL REFERENCES disputes (id),
    from_state VARCHAR(24),
    to_state   VARCHAR(24) NOT NULL,
    actor      VARCHAR(32) NOT NULL,
    note       VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE outgoing_chargebacks (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dispute_id   BIGINT      NOT NULL REFERENCES disputes (id),
    arn          VARCHAR(23) NOT NULL,
    amount_minor BIGINT      NOT NULL,
    currency     VARCHAR(3)  NOT NULL,
    reason_code  VARCHAR(8)  NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Generic audit trail (card status changes, imports, admin actions) ----------
CREATE TABLE audit_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(32)  NOT NULL,
    entity_id   BIGINT       NOT NULL,
    action      VARCHAR(64)  NOT NULL,
    detail      VARCHAR(512),
    actor       VARCHAR(32)  NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);
