import {App,h,button,field,select,row,form,modal,table,panel,metrics,money,badge,date,short,dl,csv,notice} from './shared.js';
const app=new App({project:'card-auth-switch',title:'Card Authorization Switch',abbr:'CA',accent:'#3b5778',tagline:'Issue. Authorize. Settle. Reconcile.',description:'Manage card accounts, authorize terminal purchases, inspect holds, settle presentments, and work disputes through their lifecycle.',views:[['overview','Overview'],['cards','Cards'],['authorizations','Authorizations'],['clearing','Clearing'],['disputes','Disputes'],['activity','Activity']]});
const rc={'00':'Approved','05':'Do not honor','14':'Invalid card','41':'Lost card','43':'Stolen card','51':'Insufficient funds','54':'Expired card','55':'Incorrect PIN','61':'Amount limit','65':'Frequency limit','75':'PIN tries exceeded','82':'Cryptogram rejected','91':'Issuer unavailable','96':'System error'};
function issue(){const d=modal('Issue card',notice('Cards use a fictional BIN and public test cryptographic keys. Opening funds belong to the development ledger.'),form([field('name','Cardholder name',{maxLength:64,placeholder:'Cardholder or account label'}),field('openingBalance','Opening balance USD',{type:'number',step:'.01',min:'0',value:'1000.00'})],'Issue card',async b=>{await app.action('cards',b,'Card issued.');d.close();await app.reload();}));}
function authorize(){const cards=app.data.cards.filter(c=>c.status==='ACTIVE');if(!cards.length){app.toast('Issue an active card before authorizing a purchase.','error');return;}const d=modal('New authorization',form([select('card','Card',cards.map(c=>[c.id,`${c.holderName} · •••• ${c.last4} · ${money(c.account.availableMinor)}`])),row(field('amount','Amount USD',{type:'number',min:'.01',step:'.01'}),field('merchant','Merchant name',{maxLength:40,placeholder:'Bluebird Market'})),row(select('mode','Entry mode',[['chip-pin','Chip + PIN'],['chip','Chip'],['magstripe','Magnetic stripe']]),select('verification','Verification input',[['valid','Valid card data'],['wrong-pin','Incorrect PIN'],['tampered','Tampered cryptogram']]))],'Send authorization',async b=>{const result=await app.action(`cards/${b.card}/authorize`,b,'Authorization received.');d.close();await app.reload();authDetail(app.data.transactions.find(a=>a.id===result.id)||result);}));}
function cardDetail(c){const deposit=()=>{const d=modal('Add funds · '+c.holderName,form([field('amount','Amount USD',{type:'number',step:'.01',min:'.01'})],'Add funds',async b=>{await app.action(`cards/${c.id}/deposit`,b,'Funds posted.');d.close();await app.reload();}));};const change=()=>{const d=modal('Change card status',form([select('status','Status',['ACTIVE','BLOCKED','LOST','STOLEN','CLOSED'],c.status),field('reason','Reason',{maxLength:140})],'Update status',async b=>{await app.action(`cards/${c.id}/status`,b,'Card status updated.');d.close();await app.reload();}));};modal(c.holderName,h('div',{class:'card-chip'},h('small',{},'DEVELOPMENT CARD · VISA CVN 18'),h('strong',{},'•••• •••• •••• '+c.last4),h('small',{},c.holderName+' · Expiry '+c.expiry.slice(2)+'/'+c.expiry.slice(0,2))),dl([['Status',badge(c.status)],['Available',money(c.account.availableMinor)],['Ledger balance',money(c.account.ledgerBalanceMinor)],['Held',money(c.account.heldMinor)],['Per-transaction limit',money(c.perTxnLimitMinor)],['Account ID',c.accountId]]),h('br'),h('div',{class:'actions'},button('Add funds',()=>{document.querySelector('dialog').close();deposit();}),button('Change status',()=>{document.querySelector('dialog').close();change();},'secondary')),h('h3',{},'Account holds'),table(['Merchant','Amount','Held','Status','Expires'],c.account.holds.map(a=>[a.merchantName,money(a.amountMinor),money(a.heldMinor),badge(a.status),date(a.expiresAt)])),h('h3',{},'Recent postings'),table(['When','Type','Amount','Direction','Reference'],c.account.recentPostings.map(p=>[date(p.createdAt),p.entryType,money(p.amountMinor),p.direction,short(p.reference)])));}
function authDetail(a){const d=modal('Authorization '+short(a.id),dl([['Status',badge(a.status)],['Card','•••• '+a.cardLast4],['Merchant',a.merchant],['Amount',money(a.amountMinor)],['Response',a.responseCode+' · '+(rc[a.responseCode]||'Unknown')],['Issuer cryptogram',a.arpcVerified?'Verified':a.mode==='magstripe'?'Not applicable':'Not verified'],['Entry mode',a.mode],['Latency',a.latencyMs.toFixed(1)+' ms'],['Approval code',a.authCode||'—'],['RRN',a.rrn],['Created',date(a.createdAt)],['Presentment ID',a.recordId||'Not settled']]));if(a.status==='AUTHORIZED')d.querySelector('.dialog-body').append(h('br'),notice('The amount remains held until reversed or settled. Settlement posts the purchase to the cardholder ledger.'),h('div',{class:'actions'},button('Settle purchase',async()=>{try{await app.action(`authorizations/${a.id}/settle`,{},'Purchase settled.');d.close();await app.reload();}catch(e){app.toast(e.message,'error');}}),button('Reverse authorization',async()=>{try{await app.action(`authorizations/${a.id}/reverse`,{},'Authorization reversed.');d.close();await app.reload();}catch(e){app.toast(e.message,'error');}},'secondary')));}
function openDispute(){const settled=app.data.transactions.filter(a=>a.status==='SETTLED');if(!settled.length){app.toast('Settle a purchase before opening a dispute.','error');return;}const options=settled.map(a=>[a.id,`${a.merchant} · ${money(a.amountMinor)} · ${short(a.id)}`]),sel=select('authorizationId','Settled transaction',options),amt=field('amount','Disputed amount USD',{type:'number',step:'.01',min:'.01',value:(settled[0].amountMinor/100).toFixed(2)});sel.querySelector('select').addEventListener('change',()=>amt.querySelector('input').value=(settled.find(a=>a.id===sel.querySelector('select').value).amountMinor/100).toFixed(2));const d=modal('Open dispute',form([sel,select('reasonCode','Reason',[['13.1','13.1 · Merchandise or services not received'],['13.3','13.3 · Not as described'],['12.6.1','12.6.1 · Duplicate processing'],['10.4','10.4 · Card-absent fraud']]),amt,field('note','Case note',{maxLength:1000})],'Open dispute',async b=>{await app.action('disputes',b,'Dispute opened.');d.close();await app.reload();app.go('disputes');}));}
function disputeDetail(c){
 const closed=c.state.startsWith('CLOSED_'),d=modal(c.disputeRef,dl([['State',badge(c.state)],['Amount',money(c.amountMinor)],['Reason',c.reasonCode+' · '+c.reasonDescription],['Chargeback deadline',c.chargebackDeadline||'—'],['Representment deadline',c.representmentDeadline||'—'],['Pre-arbitration deadline',c.prearbDeadline||'—']]),h('h3',{},'Evidence'),table(['Type','Description','Submitted by','When'],c.evidence.map(e=>[e.type,e.description,e.submittedBy,date(e.at)])));
 const body=d.querySelector('.dialog-body'),actions=h('div',{class:'actions'});
 const submit=async(route,data,message)=>{await app.action(`disputes/${c.id}/${route}`,data,message);d.close();await app.reload();disputeDetail(app.data.disputes.find(x=>x.id===c.id));};
 if(!closed)body.append(h('h3',{},'Add evidence'),form([select('type','Evidence type',['CARDHOLDER_LETTER','CARDHOLDER_FRAUD_DECLARATION','TRANSACTION_RECORDS']),field('description','Evidence description',{maxLength:1000})],'Attach evidence',b=>submit('evidence',b,'Evidence attached.')));
 if(c.state==='OPENED')actions.append(button('Raise chargeback',async()=>{try{await submit('chargeback',{},'Chargeback raised.');}catch(e){app.toast(e.message,'error');}}));
 if(c.state==='CHARGEBACK_SENT')body.append(h('br'),notice('Awaiting network clearing. In this development network, record the settlement to process the chargeback file and post the ledger entries.'),form([],'Record network settlement',()=>submit('network-settlement',{},'Chargeback settled through clearing.')));
 if(c.state==='CHARGEBACK_SETTLED')body.append(h('br'),notice('The chargeback has settled. Record an acquirer representment if the merchant contests it; otherwise the case awaits its representment deadline.'),form([field('reason','Acquirer representment reason',{maxLength:140})],'Record representment',b=>submit('representment',b,'Representment processed.')));
 const resolutions={OPENED:[['WITHDRAW','Withdraw']],REPRESENTED:[['ACCEPT_REPRESENTMENT','Accept representment'],['WRITE_OFF','Write off'],['ESCALATE','Escalate to pre-arbitration']],PRE_ARBITRATION:[['PREARB_WON','Pre-arbitration won'],['PREARB_LOST','Pre-arbitration lost'],['WRITE_OFF','Write off']]};
 if(resolutions[c.state])actions.append(button('Resolve dispute',()=>{d.close();const f=modal('Resolve '+c.disputeRef,form([select('action','Resolution',resolutions[c.state]),field('note','Resolution note',{maxLength:1000})],'Record resolution',async b=>{await app.action(`disputes/${c.id}/resolve`,b,'Resolution recorded.');f.close();await app.reload();}));},'secondary'));
 body.append(h('br'),actions,h('h3',{},'State history'),h('ol',{class:'timeline'},c.events.map(e=>h('li',{},h('strong',{},(e.fromState||'NEW')+' → '+e.toState),h('p',{},e.note),h('small',{},date(e.at)+' · '+e.actor)))));
}
const authRows=items=>items.map(a=>[date(a.createdAt),'•••• '+a.cardLast4,a.merchant,money(a.amountMinor),badge(a.status),a.responseCode+' · '+(rc[a.responseCode]||'Unknown'),a.latencyMs.toFixed(1)+' ms',button('Inspect',()=>authDetail(a),'secondary small')]);
app.renderView=(page,d)=>{
 if(page==='cards')return [app.head('Cards','Issue cards, manage status, add funds, and inspect account holds.',[button('Issue card',issue)]),panel('',table(['Cardholder','Card','Status','Available','Held','Ledger balance',''],d.cards.map(c=>[c.holderName,'•••• '+c.last4,badge(c.status),money(c.account.availableMinor),money(c.account.heldMinor),money(c.account.ledgerBalanceMinor),button('Manage',()=>cardDetail(c),'secondary small')]),'Issue your first card to start managing its account.'))];
 if(page==='authorizations')return [app.head('Authorizations','Live terminal requests through the Rust switch, HSM, and Java issuer.',[button('Export CSV',()=>csv('authorizations.csv',['Date','Card last4','Merchant','Amount minor','Status','Response code','Approval code','RRN'],d.transactions.map(a=>[a.createdAt,a.cardLast4,a.merchant,a.amountMinor,a.status,a.responseCode,a.authCode,a.rrn])),'secondary'),button('New authorization',authorize)]),panel('',table(['When','Card','Merchant','Amount','Status','Response','Latency',''],authRows(d.transactions),'Your authorization history will appear here.'))];
 if(page==='clearing')return [app.head('Clearing','Settle approved purchases or reverse outstanding reservations.'),metrics([['Awaiting settlement',d.transactions.filter(a=>a.status==='AUTHORIZED').length,'Approved holds'],['Settled purchases',d.transactions.filter(a=>a.status==='SETTLED').length,'Posted presentments'],['Reversed',d.transactions.filter(a=>a.status==='REVERSED').length,'Released authorizations'],['Ledger check',d.ledger.balanced&&d.ledger.balancesMatch?'Balanced':'Review required','Double-entry postings and stored balances']]),panel('',table(['When','Card','Merchant','Amount','Status','Response','Latency',''],authRows(d.transactions.filter(a=>a.status!=='DECLINED'))))];
 if(page==='disputes')return [app.head('Disputes','Evidence, reason codes, deadlines, and chargeback state transitions.',[button('Open dispute',openDispute)]),panel('',table(['Reference','Reason','Amount','State','Chargeback deadline',''],d.disputes.map(c=>[c.disputeRef,c.reasonCode,money(c.amountMinor),badge(c.state),c.chargebackDeadline,button('Work case',()=>disputeDetail(c),'secondary small')]),'Settle a purchase, then open a dispute against its presentment.'))];
 if(page==='activity')return [app.head('Activity','A record of card, authorization, clearing, and dispute operations.'),app.activity()];
 return [app.head('Overview','Card accounts, authorization activity, and settlement readiness.',[button('Refresh',()=>app.reload(),'secondary'),button(d.cards.length?'New authorization':'Issue card',d.cards.length?authorize:issue)]),metrics([['Available funds',money(d.cards.reduce((n,c)=>n+c.account.availableMinor,0)),'Across your card accounts'],['Outstanding holds',money(d.cards.reduce((n,c)=>n+c.account.heldMinor,0)),'Approved, unsettled purchases'],['Active cards',d.cards.filter(c=>c.status==='ACTIVE').length,'Ready for terminal transactions'],['Approval rate',d.transactions.length?(100*d.transactions.filter(a=>a.responseCode==='00').length/d.transactions.length).toFixed(1)+'%':'—','Your authorization history']]),h('div',{class:'columns'},panel('Recent authorizations',table(['When','Card','Merchant','Amount','Status','Response','Latency',''],authRows(d.transactions.slice(0,6)),'Issue a card and authorize your first purchase.')),panel('Reconciliation',dl([['Double-entry ledger',d.ledger.balanced?'Balanced':'Out of balance'],['Stored balances',d.ledger.balancesMatch?'Match postings':'Mismatch'],['Ready to settle',d.transactions.filter(a=>a.status==='AUTHORIZED').length],['Open disputes',d.disputes.filter(c=>!c.state.startsWith('CLOSED_')).length]]),h('br'),button('Open clearing queue',()=>app.go('clearing'),'secondary')))];
};app.start();
